# Generated by Django 4.2.3 on 2023-07-31 16:13

from django.conf import settings
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cryptocurrency', '0002_alter_cryptocurrency_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_range', django.contrib.postgres.fields.ranges.DateTimeRangeField(verbose_name='\n                                               this is time range for store the range of time that user want to send data\n                                               ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedulers', to='cryptocurrency.cryptocurrency', verbose_name='the crypto of scheduler')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedulers', to=settings.AUTH_USER_MODEL, verbose_name='the owner of scheduler')),
            ],
            options={
                'verbose_name_plural': 'schedulers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner'], name='scheduler_s_owner_i_25a9f8_idx'), models.Index(fields=['created_at'], name='scheduler_s_created_a672f8_idx')],
            },
        ),
    ]
