# Generated by Django 4.2.3 on 2023-09-16 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedulers', to=settings.AUTH_USER_MODEL, verbose_name='the owner of scheduler'),
        ),
        migrations.AddIndex(
            model_name='scheduler',
            index=models.Index(fields=['owner'], name='scheduler_s_owner_i_25a9f8_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduler',
            index=models.Index(fields=['created_at'], name='scheduler_s_created_a672f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduler',
            unique_together={('owner', 'crypto')},
        ),
    ]
