# Generated by Django 4.2.3 on 2023-08-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='time_range',
            field=models.IntegerField(verbose_name='\n                                               this is time range for store the range of time that user want to send data\n                                               '),
        ),
    ]
