# Generated by Django 4.2.3 on 2023-09-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('rank', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=13)),
                ('circulating_supply', models.BigIntegerField(blank=True, null=True)),
                ('volume_24h', models.BigIntegerField()),
                ('percent_change_24h', models.FloatField(blank=True, null=True)),
                ('percent_change_1h', models.FloatField(blank=True, null=True)),
                ('percent_change_7d', models.FloatField(blank=True, null=True)),
                ('market_cap', models.FloatField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'cryptocurrencies',
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['rank'], name='cryptocurre_rank_8fbcb6_idx'), models.Index(fields=['symbol'], name='cryptocurre_symbol_b8bdba_idx'), models.Index(fields=['created_at'], name='cryptocurre_created_88642c_idx')],
            },
        ),
    ]
