# Generated by Django 4.2.3 on 2023-07-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('rank', models.IntegerField()),
                ('circulating_supply', models.BigIntegerField()),
                ('total_supply', models.BigIntegerField()),
                ('volume_24h', models.IntegerField()),
                ('percent_change_24h', models.FloatField()),
                ('percent_change_1h', models.FloatField()),
                ('percent_change_7d', models.FloatField()),
                ('market_cap', models.FloatField()),
                ('last_update', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
            ],
        ),
    ]
