# Generated by Django 4.2.3 on 2023-07-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptocurrency',
            options={'ordering': ['rank'], 'verbose_name_plural': 'cryptocurrencies'},
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='circulating_supply',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='percent_change_1h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='percent_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='percent_change_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='rank',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='total_supply',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='cryptocurrency',
            index=models.Index(fields=['rank'], name='cryptocurre_rank_8fbcb6_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptocurrency',
            index=models.Index(fields=['symbol'], name='cryptocurre_symbol_b8bdba_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptocurrency',
            index=models.Index(fields=['created_at'], name='cryptocurre_created_88642c_idx'),
        ),
    ]
