# Generated by Django 4.2.3 on 2023-08-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0002_alter_cryptocurrency_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=13),
        ),
    ]
