# Generated by Django 4.2.3 on 2023-08-20 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0004_alter_cryptocurrency_volume_24h'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='total_supply',
        ),
    ]
