version: '3.9'

services:
  web:
    build: .
    ports:
      - 8000:8000

    env_file:
      - .env

    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate  && python3 manage.py crontab add && gunicorn coinster.wsgi --bind 0.0.0.0:8000"
    networks:
      - db

    volumes:
      - .:/app


  db:
    image: postgres
    env_file:
      - .env

    ports:
    - 5432:5432

    networks:
      - db

    volumes:
      - data:/var/lib/postgresql/data


networks:
  db:

volumes:
  data: 