version: '3.9'

services:
  web:
    build: .
    ports:
      - 8000:8000

    env_file:
      - .env

    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate  && python3 manage.py crontab add &&uvicorn coinster.asgi:application --host 0.0.0.0 --ws websockets"
    networks:
      - db

    volumes:
      - .:/app


  db:
    image: postgres
    env_file:
      - .env

    ports:
      - 5432:5432

    networks:
      - db

    volumes:
      - data:/var/lib/postgresql/data
  
  redis:
    restart: unless-stopped
    image: redis:alpine
    ports:
      - 6379:6379
    expose:
      - 6379
  
  celery:
    build: .
    command: celery -A coinster worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
  celery-beat:
    build: .
    command: celery -A coinster beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    networks:
      - db

networks:
  db:


volumes:
  data: 